import 'package:hive/hive.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

part 'product_model.g.dart'; // This file will be generated by Hive

@HiveType(typeId: 0)
class ProductModel extends HiveObject {
  @HiveField(0)
  String code;


  @HiveField(2)
  String title;



  @HiveField(4)
  String description;

  @HiveField(5)
  String category;

  @HiveField(6)
  String image;




  ProductModel({

    required this.code,
    required this.title,
    required this.description,
    required this.category,
    required this.image,

  });

  // Convert Firestore document to ProductModel
  factory ProductModel.fromDocument(DocumentSnapshot doc) {
    Map<String, dynamic> data = doc.data() as Map<String, dynamic>;
    return ProductModel(
      code: doc.id,
   
      title: data['name'],
      description: data['description'],
      category: data['category'],
      image: data['imageUrl'],
     
    );
  }
  factory ProductModel.fromMap(Map<String, dynamic> data) {
    return ProductModel(
      code: data['parcode'],
     
      title: data['name'],
      description: data['description'],
      category: data['category'],
      image: data['imageUrl'],
      
    );
  }
  // Convert ProductModel to map for Firebase
  Map<String, dynamic> toMap() {
    return {
      'name': title,
 
      'description': description,
      'category': category,
      'imageUrl': image,
      
     
    };
  }
}
