// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJHyV4VY60D6E--aEw3Xj_MfQ4wOAu39w',
    appId: '1:524172959723:web:fd0e727e243f42114683ae',
    messagingSenderId: '524172959723',
    projectId: 'temp-d8860',
    authDomain: 'temp-d8860.firebaseapp.com',
    storageBucket: 'temp-d8860.firebasestorage.app',
    measurementId: 'G-24SLNGHMLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ9YZBSRfgt83IyCTnME1A1fHAbICcZlY',
    appId: '1:524172959723:android:5e472f9603af4b614683ae',
    messagingSenderId: '524172959723',
    projectId: 'temp-d8860',
    storageBucket: 'temp-d8860.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLlU433EEs-seetaOAqHhvgtG46K2dUKc',
    appId: '1:524172959723:ios:d16c3628b6706f894683ae',
    messagingSenderId: '524172959723',
    projectId: 'temp-d8860',
    storageBucket: 'temp-d8860.firebasestorage.app',
    iosClientId: '524172959723-iepgiu8vh59fcd7rm2ti5culr0sunf9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.myVisitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLlU433EEs-seetaOAqHhvgtG46K2dUKc',
    appId: '1:524172959723:ios:d16c3628b6706f894683ae',
    messagingSenderId: '524172959723',
    projectId: 'temp-d8860',
    storageBucket: 'temp-d8860.firebasestorage.app',
    iosClientId: '524172959723-iepgiu8vh59fcd7rm2ti5culr0sunf9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.myVisitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJHyV4VY60D6E--aEw3Xj_MfQ4wOAu39w',
    appId: '1:524172959723:web:b5afc1d26b0f08b04683ae',
    messagingSenderId: '524172959723',
    projectId: 'temp-d8860',
    authDomain: 'temp-d8860.firebaseapp.com',
    storageBucket: 'temp-d8860.firebasestorage.app',
    measurementId: 'G-7LE516WFY8',
  );

}